vich_uploader:
    db_driver: orm

    mappings:
        image:
           uri_prefix: /upload/thumbnail
           upload_destination: '%kernel.project_dir%/public/upload/thumbnail'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
